version: "3.9"

services:
  db:
    image: postgres:15
    container_name: crm-postgres
    restart: always
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crm-backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/crm

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crm-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
    - ./frontend:/app
    - /app/node_modules

volumes:
  pgdata:
